// STEP Footwear App - Mock Data
// Sample product data for development and testing

import { Product, Category } from '../types';

export const mockCategories: Category[] = [
    {
        id: '1',
        name: 'Running',
        slug: 'running',
        description: 'High-performance running shoes for every terrain',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
        productCount: 24,
        isActive: true,
        sortOrder: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Casual',
        slug: 'casual',
        description: 'Everyday comfort meets style',
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400',
        productCount: 36,
        isActive: true,
        sortOrder: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'Formal',
        slug: 'formal',
        description: 'Elegant shoes for professional settings',
        image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400',
        productCount: 18,
        isActive: true,
        sortOrder: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        name: 'Limited Edition',
        slug: 'limited-edition',
        description: 'Exclusive drops and collaborations',
        image: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=400',
        productCount: 8,
        isActive: true,
        sortOrder: 4,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        name: 'Sports',
        slug: 'sports',
        description: 'Athletic footwear for peak performance',
        image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
        productCount: 28,
        isActive: true,
        sortOrder: 5,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '6',
        name: 'Sneakers',
        slug: 'sneakers',
        description: 'Trendy sneakers for street style',
        image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400',
        productCount: 42,
        isActive: true,
        sortOrder: 6,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'Air Max Velocity',
        brand: 'STEP Athletics',
        description: 'Experience unparalleled comfort with our flagship running shoe. The Air Max Velocity features advanced cushioning technology and breathable mesh upper for maximum performance. Perfect for long-distance running and daily training.',
        shortDescription: 'Premium running shoes with advanced cushioning',
        price: 8999,
        originalPrice: 12999,
        currency: 'INR',
        categoryId: '1',
        categoryName: 'Running',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', alt: 'Air Max Velocity - Side View', isPrimary: true },
            { id: '2', url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600', alt: 'Air Max Velocity - Top View', isPrimary: false },
            { id: '3', url: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600', alt: 'Air Max Velocity - Angle', isPrimary: false },
        ],
        variants: [
            { id: 'v1', color: 'Red', colorCode: '#E53935', size: 'UK 7', stock: 15, sku: 'AMV-RED-7', images: [] },
            { id: 'v2', color: 'Red', colorCode: '#E53935', size: 'UK 8', stock: 12, sku: 'AMV-RED-8', images: [] },
            { id: 'v3', color: 'Red', colorCode: '#E53935', size: 'UK 9', stock: 8, sku: 'AMV-RED-9', images: [] },
            { id: 'v4', color: 'Black', colorCode: '#212121', size: 'UK 7', stock: 20, sku: 'AMV-BLK-7', images: [] },
            { id: 'v5', color: 'Black', colorCode: '#212121', size: 'UK 8', stock: 18, sku: 'AMV-BLK-8', images: [] },
            { id: 'v6', color: 'White', colorCode: '#FAFAFA', size: 'UK 8', stock: 5, sku: 'AMV-WHT-8', images: [] },
        ],
        sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
        colors: [
            { name: 'Red', code: '#E53935' },
            { name: 'Black', code: '#212121' },
            { name: 'White', code: '#FAFAFA' },
        ],
        rating: 4.8,
        reviewCount: 256,
        isFeatured: true,
        isNew: false,
        isOnSale: true,
        tags: ['running', 'cushioned', 'breathable'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Urban Street Classic',
        brand: 'STEP Lifestyle',
        description: 'The perfect blend of comfort and style. Our Urban Street Classic sneakers feature a timeless design with modern comfort technology. Ideal for everyday wear.',
        shortDescription: 'Classic street-style sneakers',
        price: 5999,
        currency: 'INR',
        categoryId: '6',
        categoryName: 'Sneakers',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600', alt: 'Urban Street Classic', isPrimary: true },
            { id: '2', url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600', alt: 'Urban Street Classic - Angle', isPrimary: false },
        ],
        variants: [
            { id: 'v1', color: 'White', colorCode: '#FAFAFA', size: 'UK 7', stock: 25, sku: 'USC-WHT-7', images: [] },
            { id: 'v2', color: 'White', colorCode: '#FAFAFA', size: 'UK 8', stock: 22, sku: 'USC-WHT-8', images: [] },
            { id: 'v3', color: 'Navy', colorCode: '#15173D', size: 'UK 8', stock: 14, sku: 'USC-NVY-8', images: [] },
        ],
        sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10'],
        colors: [
            { name: 'White', code: '#FAFAFA' },
            { name: 'Navy', code: '#15173D' },
            { name: 'Grey', code: '#757575' },
        ],
        rating: 4.6,
        reviewCount: 189,
        isFeatured: true,
        isNew: true,
        isOnSale: false,
        tags: ['casual', 'sneakers', 'classic'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'Executive Oxford',
        brand: 'STEP Premium',
        description: 'Handcrafted leather oxford shoes for the modern professional. Features genuine leather upper, cushioned insole, and durable rubber outsole.',
        shortDescription: 'Premium leather formal shoes',
        price: 12999,
        originalPrice: 15999,
        currency: 'INR',
        categoryId: '3',
        categoryName: 'Formal',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600', alt: 'Executive Oxford', isPrimary: true },
        ],
        variants: [
            { id: 'v1', color: 'Brown', colorCode: '#5D4037', size: 'UK 7', stock: 10, sku: 'EXO-BRN-7', images: [] },
            { id: 'v2', color: 'Brown', colorCode: '#5D4037', size: 'UK 8', stock: 8, sku: 'EXO-BRN-8', images: [] },
            { id: 'v3', color: 'Black', colorCode: '#212121', size: 'UK 8', stock: 12, sku: 'EXO-BLK-8', images: [] },
        ],
        sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10'],
        colors: [
            { name: 'Brown', code: '#5D4037' },
            { name: 'Black', code: '#212121' },
        ],
        rating: 4.9,
        reviewCount: 74,
        isFeatured: true,
        isNew: false,
        isOnSale: true,
        tags: ['formal', 'leather', 'oxford'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        name: 'Cloud Runner Pro',
        brand: 'STEP Athletics',
        description: 'Lightweight and responsive running shoes designed for speed. Features our proprietary cloud cushioning technology for a bouncy, energized feel.',
        shortDescription: 'Professional racing shoes',
        price: 11499,
        currency: 'INR',
        categoryId: '1',
        categoryName: 'Running',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600', alt: 'Cloud Runner Pro', isPrimary: true },
            { id: '2', url: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600', alt: 'Cloud Runner Pro - Detail', isPrimary: false },
        ],
        variants: [
            { id: 'v1', color: 'Blue', colorCode: '#1976D2', size: 'UK 8', stock: 18, sku: 'CRP-BLU-8', images: [] },
            { id: 'v2', color: 'Orange', colorCode: '#F57C00', size: 'UK 9', stock: 15, sku: 'CRP-ORG-9', images: [] },
        ],
        sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
        colors: [
            { name: 'Blue', code: '#1976D2' },
            { name: 'Orange', code: '#F57C00' },
            { name: 'Black', code: '#212121' },
        ],
        rating: 4.7,
        reviewCount: 142,
        isFeatured: false,
        isNew: true,
        isOnSale: false,
        tags: ['running', 'lightweight', 'racing'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        name: 'Limited Edition Collab X',
        brand: 'STEP x Designer',
        description: 'An exclusive collaboration with renowned designer. Limited to 500 pairs worldwide. Features unique artistic design and premium materials.',
        shortDescription: 'Exclusive designer collaboration',
        price: 24999,
        currency: 'INR',
        categoryId: '4',
        categoryName: 'Limited Edition',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600', alt: 'Limited Edition Collab X', isPrimary: true },
        ],
        variants: [
            { id: 'v1', color: 'Multi', colorCode: '#982598', size: 'UK 8', stock: 3, sku: 'LEC-MUL-8', images: [] },
            { id: 'v2', color: 'Multi', colorCode: '#982598', size: 'UK 9', stock: 2, sku: 'LEC-MUL-9', images: [] },
        ],
        sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10'],
        colors: [
            { name: 'Multi', code: '#982598' },
        ],
        rating: 5.0,
        reviewCount: 28,
        isFeatured: true,
        isNew: true,
        isOnSale: false,
        tags: ['limited', 'exclusive', 'collector'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '6',
        name: 'Trail Blazer X',
        brand: 'STEP Outdoor',
        description: 'Rugged trail running shoes built for extreme terrain. Features aggressive tread pattern, rock plate, and waterproof upper.',
        shortDescription: 'All-terrain trail running shoes',
        price: 9499,
        currency: 'INR',
        categoryId: '5',
        categoryName: 'Sports',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600', alt: 'Trail Blazer X', isPrimary: true },
        ],
        variants: [
            { id: 'v1', color: 'Green', colorCode: '#388E3C', size: 'UK 8', stock: 20, sku: 'TBX-GRN-8', images: [] },
            { id: 'v2', color: 'Grey', colorCode: '#616161', size: 'UK 9', stock: 15, sku: 'TBX-GRY-9', images: [] },
        ],
        sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11', 'UK 12'],
        colors: [
            { name: 'Green', code: '#388E3C' },
            { name: 'Grey', code: '#616161' },
            { name: 'Black', code: '#212121' },
        ],
        rating: 4.5,
        reviewCount: 98,
        isFeatured: false,
        isNew: false,
        isOnSale: false,
        tags: ['trail', 'outdoor', 'waterproof'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '7',
        name: 'Comfort Walk Plus',
        brand: 'STEP Lifestyle',
        description: 'Ultra-comfortable walking shoes with memory foam insole. Perfect for all-day wear with arch support and breathable design.',
        shortDescription: 'All-day comfort walking shoes',
        price: 4499,
        originalPrice: 5999,
        currency: 'INR',
        categoryId: '2',
        categoryName: 'Casual',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600', alt: 'Comfort Walk Plus', isPrimary: true },
        ],
        variants: [
            { id: 'v1', color: 'Beige', colorCode: '#D7CCC8', size: 'UK 7', stock: 30, sku: 'CWP-BEI-7', images: [] },
            { id: 'v2', color: 'Black', colorCode: '#212121', size: 'UK 8', stock: 25, sku: 'CWP-BLK-8', images: [] },
        ],
        sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10'],
        colors: [
            { name: 'Beige', code: '#D7CCC8' },
            { name: 'Black', code: '#212121' },
            { name: 'White', code: '#FAFAFA' },
        ],
        rating: 4.4,
        reviewCount: 312,
        isFeatured: false,
        isNew: false,
        isOnSale: true,
        tags: ['casual', 'comfort', 'walking'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '8',
        name: 'Retro High Tops',
        brand: 'STEP Heritage',
        description: 'Classic high-top sneakers with retro styling. Features canvas upper, rubber toe cap, and iconic design that never goes out of style.',
        shortDescription: 'Classic retro high-top sneakers',
        price: 3999,
        currency: 'INR',
        categoryId: '6',
        categoryName: 'Sneakers',
        images: [
            { id: '1', url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600', alt: 'Retro High Tops', isPrimary: true },
        ],
        variants: [
            { id: 'v1', color: 'Red', colorCode: '#C62828', size: 'UK 7', stock: 22, sku: 'RHT-RED-7', images: [] },
            { id: 'v2', color: 'Black', colorCode: '#212121', size: 'UK 8', stock: 28, sku: 'RHT-BLK-8', images: [] },
            { id: 'v3', color: 'White', colorCode: '#FAFAFA', size: 'UK 9', stock: 18, sku: 'RHT-WHT-9', images: [] },
        ],
        sizes: ['UK 5', 'UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
        colors: [
            { name: 'Red', code: '#C62828' },
            { name: 'Black', code: '#212121' },
            { name: 'White', code: '#FAFAFA' },
            { name: 'Navy', code: '#15173D' },
        ],
        rating: 4.6,
        reviewCount: 456,
        isFeatured: true,
        isNew: false,
        isOnSale: false,
        tags: ['retro', 'high-top', 'canvas'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export default { mockProducts, mockCategories };
